-- CONSULTA COM GROUP BY E HAVING --
-- PROJETAR O CRM DOS MÉDICOS QUE PRESCREVERAM PELO MENOS DUAS RECEITAS --
SELECT M.CRM
FROM MEDICO M
WHERE M.CPF IN (SELECT R.CPF_MEDICO
                FROM RECEITA R
                GROUP BY R.CPF_MEDICO
                HAVING COUNT(*) > 1);

-- CONSULTA COM INNER JOIN --
-- PROJETAR O CÓDIGO DOS REMÉDIOS PRESCRITOS PELO MÉDICO COM CPF '12657045898' --
SELECT REC_REM.COD
FROM RECEITA_REMEDIO REC_REM INNER JOIN RECEITA REC
ON REC.ID_RECEITA = REC_REM.ID_RECEITA
WHERE REC.CPF_MEDICO = '12657045898';

-- CONSULTA COM OUTER JOIN --
-- PROJETAR O NOME DE TODOS OS PACIENTES QUE NÃO REALIZARAM CONSULTA --
SELECT P.NOME
FROM PACIENTE P LEFT OUTER JOIN CONSULTA C
ON P.CPF = C.CPF_PACIENTE
WHERE C.CPF_MEDICO IS NULL;

-- CONSULTA COM SEMI-JOIN --
-- PROJETAR O CPF DOS PACIENTES QUE TIVERAM PELO MENOS UMA RECEITA PRESCRITA --
SELECT P.CPF
FROM PACIENTE P
WHERE EXISTS (SELECT *
              FROM RECEITA R
              WHERE R.CPF_PACIENTE = P.CPF);

-- CONSULTA COM ANTI-JOIN --
-- PROJETAR O NOME DAS CLÍNICAS QUE AINDA NÃO POSSUEM UNIDADES --
SELECT C.NOME
FROM CLINICA C
WHERE NOT EXISTS (SELECT *
                  FROM UNIDADE U
                  WHERE U.ID_CLINICA = C.ID_CLINICA);

-- SUBCONSULTA DO TIPO ESCALAR --
-- PROJETAR O CPF DOS MÉDICOS QUE REALIZARAM CONSULTA NA ÚLTIMA DATA DE CONSULTA REGISTRADA --
SELECT CPF_MEDICO
FROM CONSULTA
WHERE DATA_CONSULTA = (SELECT MAX(DATA_CONSULTA)
                       FROM CONSULTA);

-- SUBCONSULTA DO TIPO LINHA --
-- PROJETAR O NOME DOS PACIENTES QUE TIVEREM A MESMA IDADE E CONVÊNIO DO PACIENTE DE CPF '64328028901' --
SELECT NOME
FROM PACIENTE
WHERE (IDADE, CONVENIO) = (SELECT IDADE, CONVENIO
                           FROM PACIENTE
                           WHERE CPF ='64328028901');

-- SUBCONSULTA DO TIPO TABELA --
-- PROJETAR O CPF DOS PACIENTES QUE TIVERAM CONSULTA NO DIA 01/08/2023 COM O MÉDICO DE CPF '12657045898' --
SELECT CPF
FROM PACIENTE
WHERE CPF IN (SELECT CPF_PACIENTE
              FROM CONSULTA
              WHERE DATA_CONSULTA = TO_DATE('2023-08-01', 'YYYY-MM-DD')
              AND CPF_MEDICO = '12657045898');

-- OPERADORES DE CONJUNTO --
-- PROJETAR O CPF DOS PACIENTES QUE FORAM ATENDIDOS PELOS MÉDICOS DE CRM '12657045898' E '45563256413' --
SELECT CPF_PACIENTE
FROM CONSULTA
WHERE CPF_MEDICO = '12657045898'
INTERSECT
SELECT CPF_PACIENTE
FROM CONSULTA
WHERE CPF_MEDICO = '45563256413';